### ISSUE TITLE
does not work.

### ISSUE THREAD

**Issue by YaraYT** [Alygnt/NPhisher#8]
Hello, everything except the local Host does not work for me, what should I do? Please correct.
![Screenshot_2022-10-24-17-15-00-287_com termux](https://user-images.githubusercontent.com/100045329/197549350-416ded84-e7ae-48d3-b87d-c30e03d419fe.jpg)

**Comment by Alygnt** [comment]
Looks like there was a issue in authtoken so better. Do this

> Run NPhisher and install ngrok 
![Screenshot_2022-10-25-13-19-11-331_com termux](https://user-images.githubusercontent.com/77040067/197714878-6c8c572f-85f9-4e1d-a11f-a89fa8b6dd1e.jpg)
Once ngrok is installed click "Ctrl+C" and exit

> And now you need to setup ngrok token so login to ngrok.com[Ngrok website ](dashboard.ngrok.com)  and then,

> Open Menu> Your authtoken as in the screenshot
![IMG_20221025_132620](https://user-images.githubusercontent.com/77040067/197716695-939692b1-5dd2-4948-a602-2e2b2f09fb07.jpg)


> Then now copy you authtoken
![IMG_20221025_132649](https://user-images.githubusercontent.com/77040067/197716786-5eb23d68-d41a-48c1-9699-2981fd72f6d3.jpg)


> Now back in Termux 
-Open NPhisher directory
-Type `cd .server` to open server directory 
- now type `./ngrok config add-authtoken <Paste your authtoken here>`
- now to update configuration type `./ngrok config upgrade`
- and run NPhisher back it should Work 

**Now We just manually setup the ngrok, I will fix this in few days and Then i will close this issue and let you know**

Please give a star to this repo⭐

**Comment by Alygnt** [comment]
Hey YaraTY, I fixed this issue in the latest update (Version 1.3), Try it...
I have also included many new features......
